version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: django_api
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
    expose:
      - 8000
    env_file:
      - ./backend/config/.env.prod
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    container_name: postgres_db
    env_file:
      - ./backend/config/.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
