# tienda-online/docker-compose.prod.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_api
    command: gunicorn config.wsgi:application --worker-class gevent --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/config/.env.prod
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: postgres_db
    env_file:
      - ./backend/config/.env.prod.db
    volumes:
      - ./backup_data/db:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx_backend_server
    ports:
      - 8000:8000
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    environment:
      - SKIP_PREFLIGHT_CHECK=true
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
