# tienda-online/docker-compose.prod.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_api
    command: gunicorn config.wsgi:application --worker-class gevent --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
    env_file:
      - ./backend/config/.env.prod
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    volumes:
      - react_build:/frontend/build
    environment:
      - SKIP_PREFLIGHT_CHECK=true
    env_file:
      - ./frontend/.env
    networks:
      - nginx_network
      - db_network

  db:
    image: postgres:15.1-alpine
    container_name: postgres_db
    env_file:
      - ./backend/config/.env.prod.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db_network

  nginx:
    image: nginx:latest
    container_name: nginx_backend_server
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/home/app/backend/staticfiles
      - media_volume:/home/app/backend/mediafiles
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
    networks:
      - nginx_network

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  pg_data:
  react_build:
  static_volume:
  media_volume:
